export const weather = {
  GETWEATHERDATA: "GETWEATHERDATA",
  SAVEWEATHERDATA: "SAVEWEATHERDATA",
  CLEARWEATHERDATA: "CLEARWEATHERDATA",
};

export const options = {
  SAVESETTINGS: "SAVESETTINGS",
};

export const geolocation = {
  GETLOCATION: "GETLOCATION",
  SAVELOCATION: "SAVELOCATION",
};

export const selectLoc = {
  GETSELECTEDLOC: "GETSELECTEDLOC",
  CLEARSELECTEDLOC: "CLEARSELECTEDLOC",
};
